### ISSUE TITLE
Could you include EvalCrafter in metrics/datasets? 

### ISSUE THREAD

**Issue by Yaofang-Liu** [soraw-ai/Awesome-Text-to-Video-Generation#1]
Please ref to Evalcrafter for more information. 
Webpage: https://evalcrafter.github.io/
Dataset: https://huggingface.co/datasets/RaphaelLiu/EvalCrafter_T2V_Dataset
Paper: https://arxiv.org/abs/2310.11440
GitHub: https://github.com/evalcrafter/EvalCrafter

Many thanks for your awesome list!!!

**Comment by ray-ruisun** [comment]
Yes, happy to do so, we will have a look, and then maybe update soon

**Comment by Yaofang-Liu** [comment]
Great. Many thanks for your time and support!
